//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextArt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextArt.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabet must contain at least one non-whitespace character..
        /// </summary>
        internal static string EAlphabetIsNullOrEmpty {
            get {
                return ResourceManager.GetString("EAlphabetIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Height must be greater than zero..
        /// </summary>
        internal static string EDesiredHeightGreaterThanZero {
            get {
                return ResourceManager.GetString("EDesiredHeightGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Width must be greater than zero..
        /// </summary>
        internal static string EDesiredWidthGreaterThanZero {
            get {
                return ResourceManager.GetString("EDesiredWidthGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Name not specified..
        /// </summary>
        internal static string EFontNotSpecified {
            get {
                return ResourceManager.GetString("EFontNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load an image first..
        /// </summary>
        internal static string ELoadImageFirst {
            get {
                return ResourceManager.GetString("ELoadImageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Font Size must be greater than or equal to Minimum Font Size..
        /// </summary>
        internal static string EMaxFontSizeGreaterThanMinFontSize {
            get {
                return ResourceManager.GetString("EMaxFontSizeGreaterThanMinFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Font Size must be greater than zero..
        /// </summary>
        internal static string EMaxFontSizeGreaterThanZero {
            get {
                return ResourceManager.GetString("EMaxFontSizeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Font Size must be greater than zero..
        /// </summary>
        internal static string EMinFontSizeGreaterThanZero {
            get {
                return ResourceManager.GetString("EMinFontSizeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter should be greater than or equal to zero..
        /// </summary>
        internal static string EScatterGreaterThanZero {
            get {
                return ResourceManager.GetString("EScatterGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Step must be greater than zero..
        /// </summary>
        internal static string EXStepGreaterThanZero {
            get {
                return ResourceManager.GetString("EXStepGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Step must be greater than zero..
        /// </summary>
        internal static string EYStepGreaterThanZero {
            get {
                return ResourceManager.GetString("EYStepGreaterThanZero", resourceCulture);
            }
        }
    }
}
